name: 'Github Homebrew Installer'
description: 'Install homebrew for your project'
inputs:
  unneeded:  # id of input
    description: 'nothing'
    required: false
    default: ''
outputs:
  nothing:
    description: "nothing"
    value: 
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/install.sh
      shell: bash
