name: 'Install Homebrew'
description: 'Install homebrew for your project'
inputs:
  unneeded:  # id of input
    description: 'nothing'
    required: false
    default: ''
outputs:
  random-number:
    description: "nothing"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/install.sh
      shell: bash
